Data specific to this indicator.

```{r}
emissions_profile_any_companies <- read_csv(path(params$input, params$emissions_profile_any_companies))
# FIXME User toy_emissions_profile_upstream_products_ecoinvent()
# See https://github.com/2DegreesInvesting/tiltToyData/pull/12
# https://github.com/2DegreesInvesting/tiltWorkflows/issues/9
emissions_profile_upstream_products <- read_csv(path(params$input, params$emissions_profile_upstream_products))
```

## Emissions profile upstream

```{r}
emissions_profile_upstream <- profile_emissions_upstream(
  companies = emissions_profile_any_companies,
  co2 = emissions_profile_upstream_products,
  europages_companies = europages_companies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_inputs = ecoinvent_inputs,
  ecoinvent_europages = ecoinvent_europages,
  isic = isic,
  low_threshold = 1 / 3,
  high_threshold = 2 / 3
)
```

## Results

```{r}
emissions_profile_upstream |>
  unnest_product() |>
  print() |> 
  write_csv(path(params$output, "emissions_profile_upstream_at_product_level.csv"))

emissions_profile_upstream |>
  unnest_company() |>
  print() |> 
  write_csv(path(params$output, "emissions_profile_upstream_at_company_level.csv"))
```

