
Data specific to this indicator.

```{r}
sector_profile_upstream_companies <- read_csv(path(params$input, params$sector_profile_upstream_companies))
sector_profile_any_scenarios <- read_csv(path(params$input, params$sector_profile_any_scenarios))
sector_profile_upstream_products <- read_csv(path(params$input, params$sector_profile_upstream_products))
```

## Sector profile upstream

`r explain_indicator()`

```{r}
sector_profile_upstream <- profile_sector_upstream(
  companies = sector_profile_upstream_companies,
  scenarios = sector_profile_any_scenarios,
  inputs = sector_profile_upstream_products,
  europages_companies = europages_companies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_inputs = ecoinvent_inputs,
  ecoinvent_europages = ecoinvent_europages,
  isic = isic
)
```

## Results

`r explain_results()`

```{r}
sector_profile_upstream |>
  unnest_product() |>
  print() |>
  write_csv(path(params$output, "sector_profile_upstream_at_product_level.csv"))

sector_profile_upstream |>
  unnest_company() |>
  print() |>
  write_csv(path(params$output, "sector_profile_upstream_at_company_level.csv"))
```

