```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This workflow runs in chunks of the `*companies` data and caches intermediate
results. This saves memory, completes faster, and allows you to resume after
interruptions.

## Setup

There is a lot to setup. See the comments and the *Reproducibility* drop-down.

```{r global}
library(dplyr, warn.conflicts = FALSE)
library(readr, warn.conflicts = FALSE)
library(rappdirs)
library(future)
library(fs)

# Masking `tiltIndicatorAfter::profile*()` to handle larger datasets by chunks
library(tiltWorkflows)

availableCores()

options(
  # Run by chunks. TODO: Try different multiples of `availableCores()`
  tiltWorkflows.chunks = params$chunks,
  # Read data quietly
  readr.show_col_types = FALSE,
  # Make printed output wider
  width = 500
)

# Enable computing over multiple workers in parallel
plan(multisession)

# If there is no folder for inputs, create the input/ with toy datasets
if (!dir_exists(params$input)) use_toy_input()

# Create a folder to save results
dir_create(params$output)
```

<details>

<summary>Reproducibility</summary>

```{r}
getwd()

params

try(dir_tree(params$input))

dir_tree(params$output)

sessioninfo::session_info()
```

</details>

