---
title: "Creating outputs for all tilt indicators"
author: "Kalash Singhal"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This workflow creates the output of all tilt indicators.

## Setup

```{r}
library(dplyr, warn.conflicts = FALSE)
library(readr, warn.conflicts = FALSE)
library(fs)
library(tiltWorkflows)

# Helper
tilt_path <- function(...) {
  path_home("Downloads", "tilt", ...)
}

dir_create(tilt_path("output"))
options(width = 500)
```

## Data

Here we use toy datasets that you should replace with your real data.

```{r}
europages_campanies <- tiltIndicatorAfter::ep_companies |>
  # TODO: Ask why the toy data has more columns than we need
  select(
    "company_name",
    "country",
    "company_city",
    "postcode",
    "address",
    "main_activity",
    "companies_id"
  )

ecoinvent_activities <- tiltIndicatorAfter::ecoinvent_activities

ecoinvent_europages <- tiltIndicatorAfter::matches_mapper

ecoinvent_inputs <- tiltIndicatorAfter::ecoinvent_inputs |>
  # TODO: Ask why the toy data has more columns than we need
  select(
    "input_activity_uuid_product_uuid",
    "exchange_name",
    "exchange_unit_name"
  ) |>
  distinct()

isic_tilt <- tiltIndicatorAfter::isic_tilt_mapper
```

## Emissions profile

```{r}
# Load data specific to this indicator
emissions_profile_any_companies <- read_csv(toy_emissions_profile_any_companies())
# FIXME User toy_emissions_profile_products_ecoinvent()
# See https://github.com/2DegreesInvesting/tiltToyData/pull/12
emissions_profile_products <- read_csv(toy_emissions_profile_products())

# Create results at product and company level
emissions_profile <- profile_emissions(
  emissions_profile_any_companies,
  emissions_profile_products,
  europages_companies = europages_campanies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_europages = ecoinvent_europages,
  isic_tilt = isic_tilt,
  low_threshold = 1 / 3,
  high_threshold = 2 / 3
)

emissions_profile_at_product_level <- emissions_profile |> 
  unnest_product()
emissions_profile_at_product_level

emissions_profile_at_company_level <- emissions_profile |> 
  unnest_company()
emissions_profile_at_company_level

emissions_profile_at_product_level |>
  write_csv(tilt_path("output", "emissions_profile_at_product_level.csv"))
emissions_profile_at_company_level |>
  write_csv(tilt_path("output", "emissions_profile_at_company_level.csv"))
```

## Emissions profile upstream

```{r}
# Load data specific to this indicator
# FIXME User toy_emissions_profile_upstream_products_ecoinvent()
# See https://github.com/2DegreesInvesting/tiltToyData/pull/12
emissions_profile_upstream_products <- read_csv(toy_emissions_profile_upstream_products())

# Create results at product and company level
emissions_profile_upstream <- profile_emissions_upstream(
  emissions_profile_any_companies,
  emissions_profile_upstream_products,
  europages_companies = europages_campanies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_inputs = ecoinvent_inputs,
  ecoinvent_europages = ecoinvent_europages,
  isic_tilt = isic_tilt,
  low_threshold = 1 / 3,
  high_threshold = 2 / 3
)

emissions_profile_upstream_at_product_level <- emissions_profile_upstream |> 
  unnest_product()
emissions_profile_upstream_at_product_level

emissions_profile_upstream_at_company_level <- emissions_profile_upstream |> 
  unnest_company()
emissions_profile_upstream_at_company_level

emissions_profile_upstream_at_product_level |>
  write_csv(tilt_path("output", "emissions_profile_upstream_at_product_level.csv"))
emissions_profile_upstream_at_company_level |>
  write_csv(tilt_path("output", "emissions_profile_upstream_at_company_level.csv"))
```

## Sector profile

```{r}
# Load data specific to this indicator
sector_profile_companies <- read_csv(toy_sector_profile_companies())
sector_profile_any_scenarios <- read_csv(toy_sector_profile_any_scenarios())

# Create results at product and company level
sector_profile <- profile_sector(
  sector_profile_companies,
  sector_profile_any_scenarios,
  europages_companies = europages_campanies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_europages = ecoinvent_europages,
  isic_tilt = isic_tilt,
  low_threshold = 1 / 3,
  high_threshold = 2 / 3
)

sector_profile_at_product_level <- sector_profile |> 
  unnest_product()
sector_profile_at_product_level

sector_profile_at_company_level <- sector_profile |> 
  unnest_company()
sector_profile_at_company_level

sector_profile_at_product_level |>
  write_csv(tilt_path("output", "sector_profile_at_product_level.csv"))
sector_profile_at_company_level |>
  write_csv(tilt_path("output", "sector_profile_at_company_level.csv"))
```

## Sector profile upstream

```{r}
# Load data specific to this indicator
sector_profile_upstream_companies <- read_csv(toy_sector_profile_upstream_companies())
sector_profile_upstream_products <- read_csv(toy_sector_profile_upstream_products())

# Create results at product and company level
sector_profile_upstream <- profile_sector_upstream(
  sector_profile_upstream_companies,
  sector_profile_any_scenarios,
  sector_profile_upstream_products,
  europages_companies = europages_campanies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_inputs = ecoinvent_inputs,
  ecoinvent_europages = ecoinvent_europages,
  isic_tilt = isic_tilt,
  low_threshold = 1 / 3,
  high_threshold = 2 / 3
)

sector_profile_upstream_at_product_level <- sector_profile_upstream |> 
  unnest_product()
sector_profile_upstream_at_product_level

sector_profile_upstream_at_company_level <- sector_profile_upstream |> 
  unnest_company()
sector_profile_upstream_at_company_level

sector_profile_upstream_at_product_level |>
  write_csv(tilt_path("output", "sector_profile_upstream_at_product_level.csv"))
sector_profile_upstream_at_company_level |>
  write_csv(tilt_path("output", "sector_profile_upstream_at_company_level.csv"))
```

## Results

```{r}
dir_tree(tilt_path("output"))
```
