---
title: "Creating outputs for all tilt indicators"
author: "Kalash Singhal"
params:
  input: "~/Downloads/tilt/input"
  output: "~/Downloads/tilt/output"
  emissions_profile_any_companies: "emissions_profile_any_companies.csv"
  emissions_profile_products: "emissions_profile_products.csv"
  emissions_profile_upstream_products: "emissions_profile_upstream_products.csv"
  sector_profile_any_scenarios: "sector_profile_any_scenarios.csv"
  sector_profile_companies: "sector_profile_companies.csv"
  sector_profile_upstream_companies: "sector_profile_upstream_companies.csv"
  sector_profile_upstream_products: "sector_profile_upstream_products.csv"
  europages_companies: "europages_companies.csv"
  ecoinvent_activities: "ecoinvent_activities.csv"
  ecoinvent_europages: "ecoinvent_europages.csv"
  ecoinvent_inputs: "ecoinvent_inputs.csv"
  isic_tilt: "isic_tilt.csv"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This workflow creates the output of all tilt indicators.

## Setup

```{r global}
library(dplyr, warn.conflicts = FALSE)
library(readr, warn.conflicts = FALSE)
library(fs)
library(tiltWorkflows)

# Helpers
# Creates a path under ~/Downloads/tilt/
tilt_path <- function(...) {
  path_home("Downloads", "tilt", ...)
}
# Tries to read a .csv, but if it doesn't exist it returns another dataset
read_csv_falling_back_to <- function(path, data) {
  if (file_exists(path)) {
    read_csv(path)
  } else {
    warning("Using ", deparse(substitute(data)), call. = FALSE)
    data
  }
}

# Create a folder to save results
dir_create(tilt_path("output"))
# Read data quietly and extend the width of printed datasets
options(readr.show_col_types = FALSE, width = 500)
```

## Data

This example defaults to using toy datasets but you may [use the
parameters](https://2degreesinvesting.github.io/tiltWorkflows/articles/using-parameters.html)
of this file to instead use your own data.

```{r}
europages_companies <- path(params$input, params$europages_companies) |> 
  read_csv_falling_back_to(tiltIndicatorAfter::ep_companies) |>
  select(
    "company_name",
    "country",
    "company_city",
    "postcode",
    "address",
    "main_activity",
    "companies_id"
  )

ecoinvent_activities <- path(params$input, params$ecoinvent_activities) |> 
  read_csv_falling_back_to(tiltIndicatorAfter::ecoinvent_activities)

ecoinvent_europages <- path(params$input, params$ecoinvent_europages) |> 
  read_csv_falling_back_to(tiltIndicatorAfter::matches_mapper)

ecoinvent_inputs <- path(params$input, params$ecoinvent_inputs) |> 
  read_csv_falling_back_to(tiltIndicatorAfter::ecoinvent_inputs) |>
  select(
    "input_activity_uuid_product_uuid",
    "exchange_name",
    "exchange_unit_name"
  ) |>
  distinct()

isic_tilt <- path(params$input, params$isic_tilt) |> 
  read_csv_falling_back_to(tiltIndicatorAfter::isic_tilt_mapper)
```

## Emissions profile

```{r}
# Load data specific to this indicator
emissions_profile_any_companies <- path(params$input, params$emissions_profile_any_companies) |> 
  read_csv_falling_back_to(read_csv(toy_emissions_profile_any_companies()))

# FIXME User toy_emissions_profile_products_ecoinvent()
# See https://github.com/2DegreesInvesting/tiltToyData/pull/12
# https://github.com/2DegreesInvesting/tiltWorkflows/issues/9
emissions_profile_products <- path(params$input, params$emissions_profile_products) |> 
  read_csv_falling_back_to(read_csv(toy_emissions_profile_products()))

# Create results at product and company level
emissions_profile <- profile_emissions(
  emissions_profile_any_companies,
  emissions_profile_products,
  europages_companies = europages_companies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_europages = ecoinvent_europages,
  isic_tilt = isic_tilt,
  low_threshold = 1 / 3,
  high_threshold = 2 / 3
)

emissions_profile_at_product_level <- emissions_profile |> 
  unnest_product()
emissions_profile_at_product_level

emissions_profile_at_company_level <- emissions_profile |> 
  unnest_company()
emissions_profile_at_company_level

emissions_profile_at_product_level |>
  write_csv(path(params$output, "emissions_profile_at_product_level.csv"))
emissions_profile_at_company_level |>
  write_csv(path(params$output, "emissions_profile_at_company_level.csv"))
```

## Emissions profile upstream

```{r}
# Load data specific to this indicator
# FIXME User toy_emissions_profile_upstream_products_ecoinvent()
# See https://github.com/2DegreesInvesting/tiltToyData/pull/12
# https://github.com/2DegreesInvesting/tiltWorkflows/issues/9
emissions_profile_upstream_products <- path(params$input, params$emissions_profile_upstream_products) |> 
  read_csv_falling_back_to(read_csv(toy_emissions_profile_upstream_products()))

# Create results at product and company level
emissions_profile_upstream <- profile_emissions_upstream(
  emissions_profile_any_companies,
  emissions_profile_upstream_products,
  europages_companies = europages_companies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_inputs = ecoinvent_inputs,
  ecoinvent_europages = ecoinvent_europages,
  isic_tilt = isic_tilt,
  low_threshold = 1 / 3,
  high_threshold = 2 / 3
)

emissions_profile_upstream_at_product_level <- emissions_profile_upstream |> 
  unnest_product()
emissions_profile_upstream_at_product_level

emissions_profile_upstream_at_company_level <- emissions_profile_upstream |> 
  unnest_company()
emissions_profile_upstream_at_company_level

emissions_profile_upstream_at_product_level |>
  write_csv(path(params$output, "emissions_profile_upstream_at_product_level.csv"))
emissions_profile_upstream_at_company_level |>
  write_csv(path(params$output, "emissions_profile_upstream_at_company_level.csv"))
```

## Sector profile

```{r}
# Load data specific to this indicator
sector_profile_companies <- path(params$input, params$sector_profile_companies) |> 
  read_csv_falling_back_to(read_csv(toy_sector_profile_companies()))

sector_profile_any_scenarios <- path(params$input, params$sector_profile_any_scenarios) |> 
  read_csv_falling_back_to(read_csv(toy_sector_profile_any_scenarios()))

# Create results at product and company level
sector_profile <- profile_sector(
  sector_profile_companies,
  sector_profile_any_scenarios,
  europages_companies = europages_companies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_europages = ecoinvent_europages,
  isic_tilt = isic_tilt,
  low_threshold = 1 / 3,
  high_threshold = 2 / 3
)

sector_profile_at_product_level <- sector_profile |> 
  unnest_product()
sector_profile_at_product_level

sector_profile_at_company_level <- sector_profile |> 
  unnest_company()
sector_profile_at_company_level

sector_profile_at_product_level |>
  write_csv(path(params$output, "sector_profile_at_product_level.csv"))
sector_profile_at_company_level |>
  write_csv(path(params$output, "sector_profile_at_company_level.csv"))
```

## Sector profile upstream

```{r}
# Load data specific to this indicator
sector_profile_upstream_companies <-path(params$input, params$sector_profile_upstream_companies) |> 
read_csv_falling_back_to(read_csv(toy_sector_profile_upstream_companies()))

sector_profile_upstream_products <- path(params$input, params$sector_profile_upstream_products) |> 
  read_csv_falling_back_to(read_csv(toy_sector_profile_upstream_products()))

# Create results at product and company level
sector_profile_upstream <- profile_sector_upstream(
  sector_profile_upstream_companies,
  sector_profile_any_scenarios,
  sector_profile_upstream_products,
  europages_companies = europages_companies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_inputs = ecoinvent_inputs,
  ecoinvent_europages = ecoinvent_europages,
  isic_tilt = isic_tilt,
  low_threshold = 1 / 3,
  high_threshold = 2 / 3
)

sector_profile_upstream_at_product_level <- sector_profile_upstream |> 
  unnest_product()
sector_profile_upstream_at_product_level

sector_profile_upstream_at_company_level <- sector_profile_upstream |> 
  unnest_company()
sector_profile_upstream_at_company_level

sector_profile_upstream_at_product_level |>
  write_csv(path(params$output, "sector_profile_upstream_at_product_level.csv"))
sector_profile_upstream_at_company_level |>
  write_csv(path(params$output, "sector_profile_upstream_at_company_level.csv"))
```

## Results

```{r}
dir_tree(tilt_path("output"))
```
